version: '3'

volumes:
  postgres_data: { }
  redis_cache_data: { }
  redis_timeline_data: { }
  redis_statistics_data: { }
  redis_processing_state_data: { }

services:
  fastapi:
    container_name: fastapi_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - MODULE_NAME=core.main
    depends_on:
      - postgres
    ports:
      - "8080:80"
    command: /start-reload.sh
    env_file:
      - .env

  postgres:
    container_name: postgres_db
    restart: always
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env

#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
